version: '2'
services:
  web:
    build: pythonapp 
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    network_mode: "host"
    depends_on:
      - db
    environment: 
      MYSQL_DB: ${MYSQL_COMPOSE_DB}
      MYSQL_USER: ${MYSQL_COMPOSE_USER}
      MYSQL_PASS: ${MYSQL_COMPOSE_PASS}
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_COMPOSE_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_COMPOSE_ROOT_PASS}
      MYSQL_USER: ${MYSQL_COMPOSE_USER}
      MYSQL_PASSWORD: ${MYSQL_COMPOSE_PASS}
